version: '3.9'

# docker portainer on windows 10
services:
  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer
    restart: always
    ports:
      - 9443:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - development
  portainer_agent:
      image: portainer/agent:latest
      container_name: portainer_agent
      restart: always
      ports:
        - 9001:9001
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /var/lib/docker/volumes:/var/lib/docker/volumes
      networks:
        - development

volumes:
  portainer_data:

networks:
  development:
    external: true


